stages:
  - deploy

deploy-pages:
  stage: deploy
  tags:
    - gpu
  script:
    - test -s public/index.html
  pages: true
  artifacts:
    paths:
      - public
  environment:
    name: production
    url: $CI_PAGES_URL
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
